# Generated by Django 4.1 on 2022-08-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='code_reffered',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ref_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='referral_code',
        ),
    ]
